INSERT INTO USR_ALIAS (USERNAME) VALUES ('DUMMY1');
INSERT INTO USR_ALIAS (USERNAME) VALUES ('DUMMY2');
INSERT INTO USR_ALIAS (USERNAME) VALUES ('DUMMY3');

INSERT INTO USR_USER (USER_ID, TITLE, FIRST_NAME, LAST_NAME, EMAIL, JOB) VALUES (1, NULL, 'JOHN', 'SNOW', 'JOHN.SNOW@GMAIL.COM', 'COMMANDER');

INSERT INTO USR_PASSWORD (PASSWORD_ID, USER_ID, PASSWORD, CREATIONDATE, EXPIRYDATE) VALUES (1, 1, 'PASSWORD', '2016-11-01 00:00:00', '2016-12-31 00:00:00');

INSERT INTO USR_ROLES (ROLE_ID, USER_ID) VALUES (1, 1);
INSERT INTO USR_ROLES (ROLE_ID, USER_ID) VALUES (2, 1);

INSERT INTO LOGIN (USERNAME, PASSWORD_ID, FAILEDLOGINCOUNTER, ENABLED) VALUES ('DUMMY1', 1, 0, TRUE);
