-- ROLE TABLE INIT
INSERT INTO ROLE (ROLE_ID, ROLE, IS_DEFAULT) VALUES (1, 'AUTHOR_ROLE', 1);
INSERT INTO ROLE (ROLE_ID, ROLE, IS_DEFAULT) VALUES (2, 'REVIEWER_ROLE', 1);
INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (3, 'EDITOR_ROLE');
INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (4, 'ADMIN_ROLE');