CREATE TABLE LOGIN(
	USERNAME VARCHAR(50),
	PASSWORDID INT(5) UNSIGNED,
	FAILEDLOGINCOUNTER TINYINT UNSIGNED NOT NULL,
	ENABLED TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES USER_ALIAS(USERNAME),
	FOREIGN KEY (PASSWORDID) REFERENCES PASSWORD(PASSWORDID)
);