CREATE TABLE LOGIN(
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD_ID INT(5) UNSIGNED NOT NULL,
	FAILEDLOGINCOUNTER TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ENABLED BOOLEAN NOT NULL DEFAULT 1,
	PRIMARY KEY (USERNAME),
	FOREIGN KEY (USERNAME) REFERENCES USR_ALIAS(USERNAME),
	FOREIGN KEY (PASSWORD_ID) REFERENCES USR_PASSWORD(PASSWORD_ID)
);