CREATE TABLE PASSWORD(
	PASSWORDID INT(5) UNSIGNED AUTO_INCREMENT,
	PASSWORD VARCHAR(150),
	SALT VARCHAR(10),
	CREATIONDATE TIMESTAMP NOT NULL,
	EXPIRYDATE TIMESTAMP NOT NULL,
	USERID INT(5) UNSIGNED,
	PRIMARY KEY(PASSWORDID),
	FOREIGN KEY (USERID) REFERENCES USER(USERID)
);