#
CREATE TABLE ROLE(
	ROLE_ID INT(1) UNSIGNED NOT NULL,
	ROLE VARCHAR(20),
	IS_DEFAULT BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY (ROLE_ID)
);
#
#
CREATE TABLE ACADEMIC_DISCIPLINES(
	ACADEMIC_DISCIPLINES_ID VARCHAR(20),
	ACADEMIC_DISCIPLINES_NAME VARCHAR(255),
	PRIMARY KEY(ACADEMIC_DISCIPLINES_ID)
);
#