INSERT INTO ROLES (ROLEID, ROLE) VALUES (1, 'USER_ROLE');
INSERT INTO ROLES (ROLEID, ROLE) VALUES (2, 'AUTHOR_ROLE');
INSERT INTO ROLES (ROLEID, ROLE) VALUES (3, 'REVIEWER_ROLE');
INSERT INTO ROLES (ROLEID, ROLE) VALUES (4, 'EDITOR_ROLE');
INSERT INTO ROLES (ROLEID, ROLE) VALUES (5, 'ADMIN_ROLE');