#
CREATE TABLE USER(
	USERID INT(5) UNSIGNED AUTO_INCREMENT,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	PHONENUMBER VARCHAR(20),
	ADDRESS VARCHAR(100),
	CITY VARCHAR(50),
	ZIPCODE VARCHAR(10),
	STATE VARCHAR(50),
	STATUSID INT(1) UNSIGNED,
	PRIMARY KEY (USERID),
	FOREIGN KEY (STATUSID) REFERENCES USER_STATUS(STATUSID)
);
#
#
CREATE TABLE USER_ALIAS(
	USERNAME VARCHAR(50),
	USERID INT(5) UNSIGNED,
	PRIMARY KEY (USERNAME),
	FOREIGN KEY (USERID) REFERENCES USER(USERID)
);
#
#
CREATE TABLE USR_PASSWORD(
	PASSWORD_ID INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_ID INT(5) UNSIGNED NOT NULL,
	PASSWORD VARCHAR(150) NOT NULL,
	CREATIONDATE TIMESTAMP NOT NULL,
	EXPIRYDATE TIMESTAMP NOT NULL,
	PRIMARY KEY (PASSWORD_ID),
	FOREIGN KEY (USER_ID) REFERENCES USR_ALIAS(USER_ID)
);
#
#
CREATE TABLE USR_ROLES(
	ROLE_ID INT(1) UNSIGNED NOT NULL,
	USER_ID INT(5) UNSIGNED NOT NULL,
	PRIMARY KEY (ROLE_ID,USER_ID),
	FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USR_ALIAS(USER_ID)
);
#